FROM ailispaw/ubuntu-essential:14.04-nodoc

RUN apt-get -q -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -q -y install --no-install-recommends python-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    pip install jubatus
